@startuml
class Journal {
+void _Display Entries()
+void _AddEntry()
+void _DisplayEntries()
+void _SaveToFile()
+void _LoadFromFile()
}

class Journalentry {
+list<entry>
+date()
+prompt
+response()
}

class journalprompt {
-string prompts()

}

class program {
+ void _Main()
+string choice()

}

Journal -> Journalentry
Journalentry -> journalprompt:"calls on"
journalprompt --> program

'The user will start the program where they will be given the options to 
'decide what they would like to do. This is done in the main being referenced
'to the journalprompt. Then it will move onto the Journal then onto the Journal
'entry. It will save the data in the program and will saved through the main
'program with the help of the journal. 


@enduml