@startuml
!include .\\csharp-prep\Prep1\Program.puml
!include .\\csharp-prep\Prep2\Program.puml
!include .\\csharp-prep\Prep3\Program.puml
!include .\\csharp-prep\Prep4\Program.puml
!include .\\csharp-prep\Prep5\Program.puml
!include .\\final\FinalProject\Program.puml
!include .\\final\Foundation1\Program.puml
!include .\\final\Foundation2\Program.puml
!include .\\final\Foundation3\Program.puml
!include .\\final\Foundation4\Program.puml
!include .\\prepare\Learning02\job.puml
!include .\\prepare\Learning02\Program.puml
!include .\\prepare\Learning02\resume.puml
!include .\\prepare\Learning03\Program.puml
!include .\\prepare\Learning04\Program.puml
!include .\\prepare\Learning05\Program.puml
!include .\\prove\Develop02\journal.puml
!include .\\prove\Develop02\journalentry.puml
!include .\\prove\Develop02\journalprompt.puml
!include .\\prove\Develop02\Program.puml
!include .\\prove\Develop03\Program.puml
!include .\\prove\Develop04\Program.puml
!include .\\prove\Develop05\Program.puml
!include .\\sandbox\Sandbox\Program.puml
!include .\\csharp-prep\Prep1\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\csharp-prep\Prep1\obj\Debug\net8.0\Prep1.AssemblyInfo.puml
!include .\\csharp-prep\Prep1\obj\Debug\net8.0\Prep1.GlobalUsings.g.puml
!include .\\csharp-prep\Prep2\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\csharp-prep\Prep2\obj\Debug\net8.0\Prep2.AssemblyInfo.puml
!include .\\csharp-prep\Prep2\obj\Debug\net8.0\Prep2.GlobalUsings.g.puml
!include .\\csharp-prep\Prep3\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\csharp-prep\Prep3\obj\Debug\net8.0\Prep3.AssemblyInfo.puml
!include .\\csharp-prep\Prep3\obj\Debug\net8.0\Prep3.GlobalUsings.g.puml
!include .\\csharp-prep\Prep4\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\csharp-prep\Prep4\obj\Debug\net8.0\Prep4.AssemblyInfo.puml
!include .\\csharp-prep\Prep4\obj\Debug\net8.0\Prep4.GlobalUsings.g.puml
!include .\\csharp-prep\Prep5\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\csharp-prep\Prep5\obj\Debug\net8.0\Prep5.AssemblyInfo.puml
!include .\\csharp-prep\Prep5\obj\Debug\net8.0\Prep5.GlobalUsings.g.puml
!include .\\final\FinalProject\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\final\FinalProject\obj\Debug\net8.0\FinalProject.AssemblyInfo.puml
!include .\\final\FinalProject\obj\Debug\net8.0\FinalProject.GlobalUsings.g.puml
!include .\\final\Foundation1\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\final\Foundation1\obj\Debug\net8.0\Foundation1.AssemblyInfo.puml
!include .\\final\Foundation1\obj\Debug\net8.0\Foundation1.GlobalUsings.g.puml
!include .\\final\Foundation2\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\final\Foundation2\obj\Debug\net8.0\Foundation2.AssemblyInfo.puml
!include .\\final\Foundation2\obj\Debug\net8.0\Foundation2.GlobalUsings.g.puml
!include .\\final\Foundation3\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\final\Foundation3\obj\Debug\net8.0\Foundation3.AssemblyInfo.puml
!include .\\final\Foundation3\obj\Debug\net8.0\Foundation3.GlobalUsings.g.puml
!include .\\final\Foundation4\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\final\Foundation4\obj\Debug\net8.0\Foundation4.AssemblyInfo.puml
!include .\\final\Foundation4\obj\Debug\net8.0\Foundation4.GlobalUsings.g.puml
!include .\\prepare\Learning02\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\prepare\Learning02\obj\Debug\net8.0\Learning02.AssemblyInfo.puml
!include .\\prepare\Learning02\obj\Debug\net8.0\Learning02.GlobalUsings.g.puml
!include .\\prepare\Learning03\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\prepare\Learning03\obj\Debug\net8.0\Learning03.AssemblyInfo.puml
!include .\\prepare\Learning03\obj\Debug\net8.0\Learning03.GlobalUsings.g.puml
!include .\\prepare\Learning04\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\prepare\Learning04\obj\Debug\net8.0\Learning04.AssemblyInfo.puml
!include .\\prepare\Learning04\obj\Debug\net8.0\Learning04.GlobalUsings.g.puml
!include .\\prepare\Learning05\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\prepare\Learning05\obj\Debug\net8.0\Learning05.AssemblyInfo.puml
!include .\\prepare\Learning05\obj\Debug\net8.0\Learning05.GlobalUsings.g.puml
!include .\\prove\Develop02\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\prove\Develop02\obj\Debug\net8.0\Develop02.AssemblyInfo.puml
!include .\\prove\Develop02\obj\Debug\net8.0\Develop02.GlobalUsings.g.puml
!include .\\prove\Develop03\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\prove\Develop03\obj\Debug\net8.0\Develop03.AssemblyInfo.puml
!include .\\prove\Develop03\obj\Debug\net8.0\Develop03.GlobalUsings.g.puml
!include .\\prove\Develop04\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\prove\Develop04\obj\Debug\net8.0\Develop04.AssemblyInfo.puml
!include .\\prove\Develop04\obj\Debug\net8.0\Develop04.GlobalUsings.g.puml
!include .\\prove\Develop05\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\prove\Develop05\obj\Debug\net8.0\Develop05.AssemblyInfo.puml
!include .\\prove\Develop05\obj\Debug\net8.0\Develop05.GlobalUsings.g.puml
!include .\\sandbox\Sandbox\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\sandbox\Sandbox\obj\Debug\net8.0\Sandbox.AssemblyInfo.puml
!include .\\sandbox\Sandbox\obj\Debug\net8.0\Sandbox.GlobalUsings.g.puml
@enduml
